insert into AWARD(name_award) 
values('Academy Awards Oscar'),
('Saturn Awards'),
('American Choreography Awards'),
('American Cinema Editors Golden Reels'),
('American Society of Cinematographers'),
('Art Directors Guild'),
('AVN (Adult Video News) Awards'),
('Critics Choice Movie Awards'),
('Directors Guild of America Awards'),
('Golden Reel Award'),
('Gotham Awards – Independent Feature Project'),
('Hollywood Film Awards'),
('Annie Awards'),
('International Press Academy'),
('Nickelodeon Kids Choice Awards'),
('Producers Guild of America Awards'),
('Taurus World Stunt Awards'),
('Young Artist Awards'),
('International Film Festival of Marrakech'),
('Cairo International Film Festival'),
('Cannes International Film Festival');